/*
  Copyright 2014 Auke-Dirk Pietersma legal
*/

#ifndef INCLUDE_XIMUAPI_ENUMERATIONS_H_
#define INCLUDE_XIMUAPI_ENUMERATIONS_H_

namespace ximu {

// <summary>
// Compatible firmware versions. Only major number required.
// </summary>
enum CompatibleFirmwareVersions{
  V10_X = 10
};

// <summary>
// Packet headers.
// </summary>
// <remarks>
// A matching enumeration exists in firmware source.
// </remarks>
enum PacketHeaders{
  ERROR,
  COMMAND,
  READ_REGISTER,
  WRITE_REGISTER,
  READ_DATETIME,
  WRITE_DATETIME,
  RAW_BATTERY_AND_THERMOMETER_DATA,
  CAL_BATTERY_AND_THERMOMETER_DATA,
  RAW_INERTIALAND_MAGNETIC_DATA,
  CAL_INERTIALAND_MAGNETIC_DATA,
  QUATERNION_DATA,
  DIGITAL_IO_DATA,
  RAW_ANALOGUE_INPUT_DATA,
  CAL_ANALOGUE_INPUT_DATA,
  PWM_OUTPUT_DATA,
  RAW_ADXL_345_BUS_DATA,
  CAL_ADXL_345_BUS_DATA,
};

// <summary>
// Command codes.
// </summary>
// <remarks>
// A matching enumeration exists in firmware source.
// </remarks> 
enum CommandCodes {
  NULL_COMMAND,
  FACTORY_RESET,
  RESET,
  SLEEP,
  RESET_SLEEP_TIMER,
  SAMPLE_GYROSCOPE_AXIS_AT_200DPS,
  CALCULATE_GYROSCOPE_SENSITIVITY,
  SAMPLE_GYROSCOPE_BIAS_TEMP1,
  SAMPLE_GYROSCOPE_BIAS_TEMP2,
  CALCULATE_GYROSCOPE_BIAS_PARAMETERS,
  SAMPLE_ACCELEROMETER_AXIS_AT_1G,
  CALCULATE_ACCELEROMETER_BIAS_AND_SENSITIVITY,
  MEASURE_MAGNETOMETER_BIAS_AND_SENSITIVITY,
  ALGORITHM_INITIALISE,
  ALGORITHM_TARE,
  ALGORITHM_CLEAR_TARE,
  ALGORITHM_INITIALISE_THEN_TARE
};



}  // namespace ximu
#endif  // INCLUDE_XIMUAPI_ENUMERATIONS_H_
