/*
  Copyright 2014 Auke-Dirk Pietersma legal
*/

#ifndef INCLUDE_XIMUAPI_ENUMERATIONS_H_
#define INCLUDE_XIMUAPI_ENUMERATIONS_H_

namespace ximu {

// <summary>
// Compatible firmware versions. Only major number required.
// </summary>
enum CompatibleFirmwareVersions{
  V10_X = 10
};

// <summary>
// Packet headers.
// </summary>
// <remarks>
// A matching enumeration exists in firmware source.
// </remarks>
enum PacketHeaders{
  ERROR,
  COMMAND,
  READ_REGISTER,
  WRITE_REGISTER,
  READ_DATETIME,
  WRITE_DATETIME,
  RAW_BATTERY_AND_THERMOMETER_DATA,
  CAL_BATTERY_AND_THERMOMETER_DATA,
  RAW_INERTIALAND_MAGNETIC_DATA,
  CAL_INERTIALAND_MAGNETIC_DATA,
  QUATERNION_DATA,
  DIGITAL_IO_DATA,
  RAW_ANALOGUE_INPUT_DATA,
  CAL_ANALOGUE_INPUT_DATA,
  PWM_OUTPUT_DATA,
  RAW_ADXL_345_BUS_DATA,
  CAL_ADXL_345_BUS_DATA,
};

// <summary>
// Command codes.
// </summary>
// <remarks>
// A matching enumeration exists in firmware source.
// </remarks> 
enum CommandCodes {
  NULL_COMMAND,
  FACTORY_RESET,
  RESET,
  SLEEP,
  RESET_SLEEP_TIMER,
  SAMPLE_GYROSCOPE_AXIS_AT_200DPS,
  CALCULATE_GYROSCOPE_SENSITIVITY,
  SAMPLE_GYROSCOPE_BIAS_TEMP1,
  SAMPLE_GYROSCOPE_BIAS_TEMP2,
  CALCULATE_GYROSCOPE_BIAS_PARAMETERS,
  SAMPLE_ACCELEROMETER_AXIS_AT_1G,
  CALCULATE_ACCELEROMETER_BIAS_AND_SENSITIVITY,
  MEASURE_MAGNETOMETER_BIAS_AND_SENSITIVITY,
  ALGORITHM_INITIALISE,
  ALGORITHM_TARE,
  ALGORITHM_CLEAR_TARE,
  ALGORITHM_INITIALISE_THEN_TARE
};

// <summary>
// Number of fractional bits used by fixed-point representations.
// </summary>
// <remarks>
// A matching enumeration exists in firmware source.
// </remarks> 
enum Qvals {
  CALIBRATED_BATTERY = 12,
  CALIBRATED_THERMOMETER = 8,
  CALIBRATED_GYROSCOPE = 4,
  CALIBRATED_ACCELEROMETER = 11,
  CALIBRATED_MAGNETOMETER = 11,
  QUATERNION = 15,
  BATTERY_SENSITIVITY = 5,
  BATTERY_BIAS = 8,
  THERMOMETER_SENSITIVITY = 6,
  THERMOMETER_BIAS = 0,
  GYROSCOPE_SENSITIVITY = 7,
  GYROSCOPE_SAMPLED_200DPS = 0,
  GYROSCOPE_BIAS_AT_25_DEGC = 3,
  GYROSCOPE_BIAS_TEMP_SENSITIVITY = 11,
  GYROSCOPESAMPLEDBIAS = 3,
  ACCELEROMETER_SENSITIVITY = 4,
  ACCELEROMETER_BIAS = 8,
  ACCELEROMETER_SAMPLED_1G = 4,
  MAGNETOMETER_SENSITIVITY = 4,
  MAGNETOMETER_BIAS = 8,
  MAGNETOMETER_HARDIRON_BIAS = 11,
  ALGORITHM_KP = 11,
  ALGORITHM_KI = 15,
  ALGORITHM_INIT_KP = 11,
  ALGORITHM_INIT_PERIOD = 11,
  CALIBRATED_ANALOGUEI_NPUT = 12,
  ANALOGUE_INPUT_SENSITIVITY = 4,
  ANALOGUE_INPUT_BIAS = 8,
  CALIBRATED_ADXL_345 = 10,
  ADXL345_BUS_SENSITIVITY = 6,
  ADXL345_BUS_BIAS = 8
};



}  // namespace ximu
#endif  // INCLUDE_XIMUAPI_ENUMERATIONS_H_
